### PR TITLE
Closes #25

### LINKED ISSUE #25: Bad initialization of cumulativeLength->NullValue line 1454 of IjkGridParametricRepresentation.cpp
Hello,

I found an issue in IjkGridParametricRepresentation.cpp. Line 1454, cumulativeLength->NullValue is not properly instantiated. 

Regards,
Mathieu

# What are the steps to reproduce this issue?
1. calling setGeometryAsParametricSplittedPillarNodesUsingExistingDatasets method with splitCoordinateLineColumnCumulativeCount (which is actually and HDF5 dataset path within this method) lenght lesser than splitCoordinateLineCount - 1

# What does happen?
Out of range error occurs line 1454 of IjkGridParametricRepresentation.cpp

# What were you expecting to happen?
I think that line 1454 is inconsistent considering that within setGeometryAsParametricSplittedPillarNodesUsingExistingDatasets, splitCoordinateLineColumnCumulativeCount parameter is an HDF5 dataset path. On my mind, the expression "splitCoordinateLineCount - 1" into brackets does not make sense. I think that this expression is a remain of the splitCoordinateLineColumnCumulativeCount unsigned int array.

# What versions of fesapi are you using?
fesapi is up to date according to december 11 2017 commit.

### PR DESCRIPTION
**Pull request by mpoudret**
Hi, 

Here is a fix proposal regarding issue #25

Regards,
Mathieu

What does this implement/fix? Explain your changes.
---------------------------------------------------
Change initialization of cumulativeLength->NullValue, line 1454 of IjkGridParametricRepresentation.cpp

Does this close any currently open issues?
------------------------------------------
I guess it fixes issue #25 

Where has this been tested?
---------------------------
Windows 10 64bits
Visualt Studio 2015 Community

### CODE REVIEW

File: src/resqml2_0_1/IjkGridParametricRepresentation.cpp [hunk 1]
```diff
@@ -1451,7 +1451,7 @@ void IjkGridParametricRepresentation::setGeometryAsParametricSplittedPillarNodes
 		// Cumulative
 		resqml2__IntegerHdf5Array* cumulativeLength = soap_new_resqml2__IntegerHdf5Array(gsoapProxy2_0_1->soap, 1);
 		geom->SplitCoordinateLines->ColumnsPerSplitCoordinateLine->CumulativeLength = cumulativeLength;
-		cumulativeLength->NullValue = splitCoordinateLineColumnCumulativeCount[splitCoordinateLineCount - 1] + 1;
+		cumulativeLength->NullValue = getPillarCount();
```
Comment (philippeVerney) [inline src/resqml2_0_1/IjkGridParametricRepresentation.cpp]: Looking at IjkGridExplicitRepresentation.cpp line 437, it looks zero has been chosen as the null value.
Zero looks to me better since it does not require any call to any method and since it should never be a valid value.

for consistency reason, I am going to modify this fix.
